# Change the colors and behavior of the different bars.

# The name will formatted like this: {prefix}{colored_mobName}{healthBar}{suffix}
# disable-mob-name: # If true, the mob will not display its name, only the health.

general:
  name-always-shown: true # If true, the name of the mob will always be shown, even if the player is not looking at the entity. Will not work with SPRITES and BARS
  display-skyblock-level: false # Display a prefix of a mob's level. [Lv5] Zombie
  disable-mob-name: false # If true, the mob will not display its name, only the health.
  name-color: "&c" # The color of the mob's name. Must be a valid Minecraft color code.

selected: SKYBLOCK # The selected bar that will be used for all mobs. Must be uppercase

bars:
  skyblock:
    prefix: ""
    suffix: "&c❤"
    display-skyblock-health: true # If true, health will be multiplied by 5. So a mob with 20 HP would display 100/100 instead of 20/20.
    color:
      high: "&a"
      mid: "&e"
      low: "&c"

  symbols:
    prefix: ""
    suffix: ""
    symbol: "■"
    color:
      high: "&a"
      mid: "&e"
      low: "&c"

  sprites:
    prefix: ""
    suffix: ""
    line-width: 200 # The width of the text display, overflow will be wrapped to a new line
    wrap-at: 10 # The amount of symbols that will be displayed before wrapping to a new line.
    sprites: # <sprite[:atlas]:sprite> | See also: https://www.gamergeeks.net/apps/minecraft/list-of-atlas-sprites
      full: "<sprite:gui:hud/heart/full>"
      half: "<sprite:gui:hud/heart/half>"

  bars:
    prefix: ""
    suffix: ""
