name: MobHealth
version: '2.0.1'
main: net.kalbskinder.mobHealth.MobHealth
author: Kalbskinder
api-version: '26.1.2'

permissions:
  mobhealth.admin:
    description: Allows access to all MobHealth commands
    default: op